CREATE TABLE IF NOT EXISTS FainaData (
    Key TEXT PRIMARY KEY,
    Value TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS Users (
    DiscordID TEXT PRIMARY KEY,
    Nome TEXT NOT NULL,
    Sexo TEXT NOT NULL,
    NMec TEXT NOT NULL,
    Matricula TEXT NOT NULL,
    NomeDeFaina TEXT NOT NULL,
    FainaCompleta BOOLEAN NOT NULL,
    NumeroAluviao TEXT DEFAULT "?" NOT NULL
);

CREATE TABLE IF NOT EXISTS Botes (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    Author TEXT NOT NULL,
    Bote TEXT NOT NULL,
    Time INTEGER NOT NULL,
    UploaderID TEXT NOT NULL,
    UploaderName TEXT
);
