CREATE TABLE IF NOT EXISTS Users (
    DiscordID TEXT PRIMARY KEY,
    Nome TEXT NOT NULL,
    Sexo TEXT NOT NULL,
    NMec INTEGER NOT NULL,
    Matricula TEXT NOT NULL,
    NomeDeFaina TEXT NOT NULL,
    FainaCompleta BOOLEAN NOT NULL,
    NumeroAluviao TEXT DEFAULT "?" NOT NULL
);

CREATE TABLE IF NOT EXISTS Verifications (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    DiscordID TEXT NOT NULL,
    Nome TEXT NOT NULL,
    Sexo TEXT NOT NULL,
    NMec INTEGER NOT NULL,
    Matricula TEXT NOT NULL,
    NomeDeFaina TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS NameChanges (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    DiscordID TEXT NOT NULL,
    NomeNovo TEXT NOT NULL
);